"use client";

import { useEffect } from "react";
import { ChevronDown, ChevronRight, Plus, Sparkles, Trash2 } from "lucide-react";
import { CurriculumNode, ADD_LABEL } from "@/lib/types";
import { useCurriculumActions } from "@/lib/CurriculumActionsContext";
import { InlineField } from "./InlineField";

const LEVEL_META: Record<
  string,
  { eyebrow: string; card: string; border: string; title: string; eyebrowColor: string }
> = {
  module: {
    eyebrow: "Module",
    card: "bg-surface shadow-card rounded-xl",
    border: "border-l-[3px] border-brand",
    title: "text-[15px]",
    eyebrowColor: "text-brand-700",
  },
  topic: {
    eyebrow: "Topic",
    card: "bg-canvas rounded-lg",
    border: "border-l-[3px] border-brand-300",
    title: "text-[14px]",
    eyebrowColor: "text-brand-600",
  },
  lesson: {
    eyebrow: "Lesson",
    card: "bg-transparent hover:bg-ink-100/60 rounded-md",
    border: "border-l-2 border-ink-200",
    title: "text-[13.5px]",
    eyebrowColor: "text-ink-500",
  },
};

export function CurriculumNodeView({ node, index }: { node: CurriculumNode; index: number }) {
  const actions = useCurriculumActions();
  const meta = LEVEL_META[node.type];
  const hasChildren = node.children.length > 0;
  const childLabel = ADD_LABEL[node.type];
  const numberLabel = `${meta.eyebrow} ${index + 1}`;

  const isNewlyCreated = actions.lastCreatedId === node.id;
  useEffect(() => {
    if (isNewlyCreated && actions.clearLastCreatedId) {
      actions.clearLastCreatedId();
    }
  }, [isNewlyCreated, actions]);

  return (
    <div className={`group/node ${meta.card} ${meta.border} pl-4 pr-3 py-2.5 mb-2`}>
      <div className="flex items-start gap-2">
        {node.type !== "lesson" ? (
          <button
            onClick={() => actions.toggleNode(node.id)}
            className="mt-1 shrink-0 text-ink-300 hover:text-ink-700 transition-colors"
            aria-label={node.collapsed ? "Expand" : "Collapse"}
          >
            {node.collapsed ? <ChevronRight size={16} /> : <ChevronDown size={16} />}
          </button>
        ) : (
          <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-ink-300" />
        )}

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`font-mono text-[10.5px] font-semibold uppercase tracking-wider ${meta.eyebrowColor}`}>
              {numberLabel}
            </span>
            {node.aiInferred && (
              <span
                className="inline-flex items-center gap-1 text-[10px] font-medium text-clinical-teal bg-clinical-tealSoft px-1.5 py-0.5 rounded"
                title="Generated by AI from surrounding context — review before relying on it"
              >
                <Sparkles size={10} /> AI-inferred
              </span>
            )}
          </div>

          <InlineField
            value={node.title}
            onChange={(v) => actions.setTitle(node.id, v)}
            placeholder={`Untitled ${meta.eyebrow.toLowerCase()}`}
            variant="title"
            className={meta.title}
            autoFocus={isNewlyCreated}
          />

          <InlineField
            value={node.description}
            onChange={(v) => actions.setDescription(node.id, v)}
            placeholder="Click to add description"
            variant="description"
            className="text-[13px] text-ink-500 mt-0.5"
          />
        </div>

        <button
          onClick={() => actions.deleteNode(node.id)}
          className="shrink-0 opacity-0 group-hover/node:opacity-100 text-ink-300 hover:text-red-500 transition-all p-1 -mr-1"
          aria-label={`Delete ${meta.eyebrow.toLowerCase()}`}
        >
          <Trash2 size={14} />
        </button>
      </div>

      {!node.collapsed && (hasChildren || childLabel) && (
        <div className="mt-2 ml-[7px] pl-4 border-l-2 border-ink-200/70">
          {node.children.map((child, i) => (
            <CurriculumNodeView key={child.id} node={child} index={i} />
          ))}

          {childLabel && (
            <button
              onClick={() => actions.addChildTo(node.id)}
              className="flex items-center gap-1.5 text-[12.5px] font-medium text-ink-500 hover:text-brand-700 px-2 py-1.5 rounded-md hover:bg-brand-50 transition-colors"
            >
              <Plus size={13} /> {childLabel}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
